version: "3.9"
services:
  web:
    build:
      context: ./services/web
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    depends_on:
      - database
      - smtp
    volumes:
      - ${SOURCE_ROOT_FOLDER}:/var/www/html
    environment:
      - "WORDPRESS_DB_HOST=database"
      - "WORDPRESS_DB_USER=${BDD_MYSQL_USER}"
      - "WORDPRESS_DB_PASSWORD=${BDD_MYSQL_PASSWORD}"
      - "WORDPRESS_DB_NAME=${BDD_MYSQL_DATABASE}"
      - "WORDPRESS_TABLE_PREFIX=mr_"

  database:
    image: mysql:5.6.50
    volumes:
      - ./services/database/data:/var/lib/mysql
      - ./services/database/import:/import
    environment:
      - "MYSQL_ROOT_PASSWORD=${BDD_MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${BDD_MYSQL_USER}"
      - "MYSQL_PASSWORD=${BDD_MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${BDD_MYSQL_DATABASE}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    environment:
      - PMA_HOST=database

  smtp:
    image: maildev/maildev
